### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by 04090904** [04090904/furima-35391#9]
自身のフリマアプリのURL | 本番環境(Heroku)のURL
## https://furima-35391.herokuapp.com/
Basic認証のIDとパスワード |  ## kazuya  ## 0409
出品者用のメールアドレスとパスワード | 本番環境で使用可能なユーザーの情報
## 1234@1234 ## a11111(nickname = メンター)
購入者用のメールアドレスとパスワード | 上記とは異なる、本番環境で使用可能なユーザーの情報

**Comment by 04090904** [comment]
## もう一人(nickname =テスト)

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン状態の出品者以外のユーザーのみ、必要な情報を適切に入力すると、商品の購入ができるようにしましょう**
必要な情報を適切に入力して購入ボタンを押しても、エラーページに遷移してしまい購入ができません。


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/117229162-697a2d80-ae55-11eb-8ba1-6fe7b2b3a440.png)
